config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/signup_patient', to: 'patients#new'
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  patch '/edit_session', to: "sessions#update"
  delete "/logout", to: "sessions#destroy"
  
  resources :patients
  resources :contents
  resources :messages
  resources :appointments
  resources :administrators
  resource :calendar, only: [:show], controller: :calendar
  
end

app/models/message.rb
class Message < ApplicationRecord
    
    validates :subject, presence: true
    validates :content, presence: true
    validates :creator_id, presence: true
    validates :creator_type, presence: true
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # _sh: sessions_helper
  
  before_action :redirect_blocked_users_sh
  before_action :logged_in_patient_sh
  
  def new
    @message=Message.new
  end
  
  def show
    @message=Message.find(params[:id])
    if ((@message.recipient_id==current_user_sh.id or @message.recipient_id==0 ) and @message.recipient_type==current_user_sh.class.to_s)
      @message.update_attribute(:seen, true)
      remember_message_sh(@message.id)
    elsif(@message.creator_id==current_user_sh.id and @message.creator_type==current_user_sh.class.to_s)
      #do nothing
    else
      redirect_to root_path
    end
  end
  
  def create
    @message=Message.new(message_params)
    if (params[:message][:creator_id]==current_user_sh.id.to_s and params[:message][:creator_type]==current_user_sh.class.to_s)
      if @message.save
        flash[:success]="Message sent"
        redirect_to current_user_sh
      else
        render "new"
      end
    else
      redirect_to root_path
    end
  end
  
  def update
    @message=current_message_sh
    if params[:seen]=="true"
      @message.update_attribute(:seen, false)
    elsif params[:seen]=="false"
      @message.update_attribute(:seen, true)
    elsif params[:processed]=="true"
      @message.update_attribute(:processed, false)
    elsif params[:processed]=="false"
      @message.update_attribute(:processed, true)
    end
    respond_to do |format|
      format.html {redirect_to messages_path}
      format.js
    end
  end

  def index
    if current_user_admin_sh?
      @messages=Message.where(recipient_type: "Administrator", recipient_id: [0, current_user_sh.id])
      @sent_messages=Message.where(creator_type: "Administrator", creator_id: current_user_sh.id)
    else
      @messages=Message.where(recipient_type: "Patient", recipient_id: [0, current_user_sh.id])
      @sent_messages=Message.where(creator_type: "Patient", creator_id: current_user_sh.id)
    end
  end
  
  private
  
  def message_params
    if current_user_admin_sh?
      params.require(:message).permit(:creator_id, :creator_type, :content, :subject, :recipient_id, :recipient_type)
    else
      params.require(:message).permit(:creator_id, :creator_type, :content, :subject, :recipient_id)
    end
  end
  
end

app/helpers/messages_helper.rb
module MessagesHelper
    
end

app/views/messages/_message.html.erb
<li id="message-<%= message.id %>">
    
    <% if message.creator_type="Administrator" %>
        <% user=Administrator.find(message.creator_id) %>
    <% else %>
        <% user=PAtient.find(message.creator_id) %>
    <% end %>
    
    <% if message.seen %>
        <span><%= link_to "#{message.subject}" + " | by: " + user.name, message_path(message) %></span>
    <% else %>
        <b><%= link_to "#{message.subject}" + " | by: " + user.name, message_path(message) %></b>
    <% end %>
</li>
<br><%= message.created_at.to_date %>

app/views/messages/_processing_buttons.html.erb
<span class="processing_button">
    <div>
        <% if @message.processed %>
            <%= link_to "Set to: In process", message_path(@message, :processed => @message.processed), method: :patch, remote: true  %>
        <% else %>
            <%= link_to "Set to: Completed", message_path(@message, :processed => @message.processed), method: :patch, remote: true %>
        <% end %>
    </div>
</span>

app/views/messages/_seen_buttons.html.erb
<span class="seen_button">
    <div>
        <% if @message.seen %>
            <%= link_to "Set to: Unseen", message_path(@message, :seen => @message.seen), method: :patch, remote: true  %>
        <% else %>
            <%= link_to "Set to: Seen", message_path(@message, :seen => @message.seen), method: :patch, remote: true %>
        <% end %>
    </div>
</span>

app/views/messages/index.html.erb
<h1>All Messages</h1>

<div class="items">
    <div class="upcomming">
        <h4>Your Messages</h4>
        <div class="items-list">    
            <ul class="messages">
                <%= render @messages %>
            </ul>
        </div>
    </div>
    
    <div class="history-dropdown">
        <h4><%= link_to "Sent Messages", "#", id: "history-link" %><b class="caret"></b></h4>
        <div class="items-list", id="history">    
            <ul class="messages">
                <% @sent_messages.each do |msg| %>
                    <%= render partial: 'messages/message', locals: {message: msg} %>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/messages/new.html.erb
<% provide(:title, 'new message') %>
<h1>New message</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@message) do |f| %>
    
        <%= render partial: 'shared/error_messages', locals: {object: @message} %>
        
        <%= f.hidden_field :creator_id, :value => current_user_sh.id %>
        
        <%= f.hidden_field :creator_type, :value => current_user_sh.class.to_s %>
        
        <% if(params[:recipient_id] and params[:recipient_type] and current_user_admin_sh?) %>
            <%= f.hidden_field :recipient_id, :value => params[:recipient_id] %>
        
            <%= f.hidden_field :recipient_type, :value => params[:recipient_type] %>
        <% elsif current_user_admin_sh? %>
            <%= f.label :recipient_id %>
            <%= f.text_field :recipient_id, class: "form-control" %>
            
            <%= f.select :recipient_type, options_for_select(["Patient", "Administrator"]) %>
        <% end %>
        
        <%= f.label :subject %>
        <%= f.text_field :subject, class: "form-control" %>
        
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", id: "content-input" %>

        <%= f.submit "Send", class: "btn btn-primary", id: "fix" %>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="message">
    <p id="subject"><%= @message.subject %></p>

    <div class="content" id="message">
        <%= @message.content %>
    </div>
    
    <div class="options">
        <div>
            <%= render "messages/seen_buttons" %>
        </div>
        
        <% if current_user_admin_sh? %>
            <div>
                <%= render "messages/processing_buttons" %>
            </div>
        <% end %>
        
        <%= link_to "Anwser", new_message_path(:recipient_id => @message.creator_id, :recipient_type => @message.creator_type) %><br>
    </div>
</div>

app/views/messages/update.js.erb
$("span.seen_button").html("<%= j render "messages/seen_buttons" %>");
$("span.processing_button").html("<%= j render "messages/processing_buttons" %>");