config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/signup_patient', to: 'patients#new'
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  patch '/edit_session', to: "sessions#update"
  delete "/logout", to: "sessions#destroy"
  
  resources :patients
  resources :contents
  resources :messages
  resources :appointments
  resources :administrators
  resource :calendar, only: [:show], controller: :calendar
  
end

app/views/shared/_blocked_warning.html.erb
<div id="blocked-user-warning">Warning, this account is blocked and restricted from taking any actions! Please contact an administrator.</div>

app/views/shared/_edit_mode.html.erb
<% if edit_session_sh? %>
    <% unless (current_page?(root_path) or current_page?(about_path)) %>
        <%= link_to "Editor mode: on", edit_session_path, method: :patch, remote: true %>
    <% else %>
        <%= link_to "Editor mode: on", edit_session_path, method: :patch %>
    <% end %>
<% else %>
    <% unless (current_page?(root_path) or current_page?(about_path)) %>
        <%= link_to "Editor mode: off", edit_session_path, method: :patch, remote: true %>
    <% else %>
        <%= link_to "Editor mode: off", edit_session_path, method: :patch %>
    <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>