config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/signup_patient', to: 'patients#new'
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  patch '/edit_session', to: "sessions#update"
  delete "/logout", to: "sessions#destroy"
  
  resources :patients
  resources :contents
  resources :messages
  resources :appointments
  resources :administrators
  resource :calendar, only: [:show], controller: :calendar
  
end

app/models/administrator.rb
class Administrator < ApplicationRecord
    validates :name, presence: true
    validates :date_birth, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,  length: {maximum:255}, format: {with: VALID_EMAIL_REGEX},
                uniqueness: {case_sensitive: false}
    validate :unique_email
    has_secure_password
    
    def forget
        return true
    end
    
    def blocked?
        return true if blocked==true
    end
    
    private
    
    def unique_email
        self.errors.add(:email, "Email already taken") if Patient.where(email: self.email).exists?
    end
    
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  # _sh: sessions_helper
  
  before_action :redirect_blocked_users_sh, except: [:show]
  before_action :logged_in_administrator_sh
  before_action :correct_administrator_or_supervisor, only: [:show]
  before_action :administrator_is_supervisor, only: [:new, :create, :destroy, :edit, :update]
  
  def new
    @administrator=Administrator.new
  end
  
  def create
    @administrator=Administrator.new(administrator_params)
    if @administrator.save
      flash[:success]="New administrator created: " + @administrator.name
      redirect_to @administrator
    else
      render "administrators/new"
    end
  end

  def show
    @administrator=Administrator.find_by(id: params[:id])
    @messages=Message.where(recipient_type: "Administrator", recipient_id: [0, params[:id].to_i])
  end
  
  def edit
      @administrator=Administrator.find(params[:id])
  end
    
  def update
      if ( user_id = params[:user_to_block] )
          @administrator=Administrator.find(user_id)
          if @administrator.supervisor==false
            if @administrator.blocked?
                @administrator.update_attribute(:blocked, false)
                flash[:success]="Profile unblocked"
                redirect_to @administrator
            else
                @administrator.update_attribute(:blocked, true)
                flash[:success]="Profile blocked"
                redirect_to @administrator
            end
          else
            flash[:danger]="Supervisors can not be blocked"
            redirect_to @administrator
          end
      else
          @administrator=Administrator.find(params[:id])
          if @administrator.update_attributes(administrator_params)
             flash[:success]="Profile updated"
             redirect_to @administrator
          else
              render 'edit'
          end
      end
  end

  def index
    @administrators=Administrator.all
  end
  
  def destroy
    if Administrator.find_by(id: params[:id]).supervisor==true
      flash[:danger] = "Supervisors can not be deleted."
      redirect_to current_user_sh
    else
      Administrator.find_by(id: params[:id]).destroy
      @id_to_delete=params[:id]
      #used in destroy.js.erb
      respond_to do |format|
        format.html do
          flash[:success]="Administrator destroyed"
          redirect_to current_user_sh
        end
        format.js do
          flash.now[:success]="Administrator deleted"
        end
      end
    end
  end
  
  private
  
  def administrator_params
    params.require(:administrator).permit(:name, :email, :phone, :adress, :date_birth, :password, :password_confirmation)
  end
  
  def correct_administrator_or_supervisor
    unless( current_user_sh?(Administrator.find_by(id: params[:id]) ) or current_user_sh.supervisor==true )
      flash[:danger]="You are not authorized to perform this action."
      redirect_to root_path
    end
  end
  
  def administrator_is_supervisor
    unless current_user_sh.supervisor==true
      flash[:danger]="You are not authorized to perform this action."
      redirect_to root_path
    end
  end
  
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_administrator.html.erb
<li id="administrator-<%= administrator.id %>">
    <%= link_to administrator.name, administrator %> 
    <br>
    <% unless administrator.supervisor %>
        <%= link_to "delete", administrator, method: :delete, 
            data: { confirm: 
            "You are about to delete this Administrator. All information lost this way can not be recovered. Continue?" }, 
            remote: true %>
    <% else %>
        Supervisor
    <% end %>
    <br><br>
</li>

app/views/administrators/destroy.js.erb
$("#administrator-<%= j @id_to_delete %>").remove();
$("#flash-container").empty();
$("#flash-container").append("<%= j render(:partial => 'layouts/flash') %>")

app/views/administrators/edit.html.erb
<% provide(:title, 'Administrator edit') %>
<h1>Edit</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@administrator) do |f| %>
    
      <%= render partial: 'shared/error_messages', locals: {object: @administrator} %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :adress %>
      <%= f.text_field :adress, class: "form-control" %>
      
      <%= f.label :phone %>
      <%= f.phone_field :phone, class: "form-control" %>
      
      <%= f.label :date_birth %>
      <%= f.date_field :date_birth, class: "form-control", placeholder: "YYYY-MM-DD" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Save changes", class: "btn btn-primary", id: "fix" %>
    <% end %>
  </div>
</div>

app/views/administrators/index.html.erb
<!--_sh session_helper-->

<h1>Administrators</h1>

<% @administrators.each do |admin| %>
    <% unless admin==current_user_sh %>
        <ul class="users">
            <%= render admin %>
        </ul>
    <% end %>
<% end %>

app/views/administrators/new.html.erb
<% provide(:title, 'administrator creation') %>
<h1>create a new adminnistrator</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@administrator) do |f| %>
    
      <%= render partial: 'shared/error_messages', locals: {object: @administrator} %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :adress %>
      <%= f.text_field :adress, class: "form-control" %>
      
      <%= f.label :phone %>
      <%= f.phone_field :phone, class: "form-control" %>
      
      <%= f.label :date_birth %>
      <%= f.date_field :date_birth, class: "form-control", placeholder: "YYYY-MM-DD" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create", class: "btn btn-primary", id: "fix" %>
    <% end %>
  </div>
</div>

app/views/administrators/show.html.erb
<% if @administrator.blocked? %>
    <%= render "shared/blocked_warning" %>
<% end %>

<div id="object-info">
    <h3><%= @administrator.name %></h3>
    <div class="info-field">
        <div class="tile"><b>Birthday: </b></div>
        <div class="tile"><%= @administrator.date_birth %></div>
    </div>
    <div class="info-field">
        <div class="tile"><b>Address: </b></div>
        <div class="tile"><%= @administrator.adress %></div>
    </div>
    <div class="info-field">
        <div class="tile"><b>Email: </b></div>
        <div class="tile"><%= @administrator.email %></div>
    </div>
    <div class="info-field">
        <div class="tile"><b>Phone: </b></div>
        <div class="tile"><%= @administrator.phone %></div>
    </div>
    
    <% if current_user_sh.supervisor==true and @administrator.supervisor!=true %>
        <section class="settings-dropdown">
            <h4><%= link_to "Settings", "#", id: "settings-link" %><b class="caret"></b></h4>
            <div class="settings">
                <%= link_to "edit", edit_administrator_path(@administrator.id)%>
                <br>
                <%= link_to "block", administrator_path(@administrator.id, :user_to_block => @administrator.id), method: :patch %>
                <br>
                <b><%= link_to "Delete Administrator", "#", id: "delete-link" %></b><b class="caret"></b>
                <div id="delete"><%= link_to "delete", @administrator, method: :delete, data: { confirm: 
                    "You are about to delete this Administrator. All information lost this way can not be recovered. Continue?"
                    } %></div>
            </div>
        </section>
    <% end %>
</div>

<div class="items">
    <div class="upcomming">
        <h4>New Messages</h4>
        <div class="items-list">    
            <ul class="messages">
                <% @messages.each do |msg| %>
                    <% unless msg.seen %>
                    
                        <% if msg.creator_type="Administrator" %>
                            <% user=Administrator.find(msg.creator_id) %>
                        <% else %>
                            <% user=PAtient.find(msg.creator_id) %>
                        <% end %>
                    
                        <li id="message-"+<%= msg.id %>><%= link_to msg.subject + " | by: " + user.name, msg %></li>
                        <br><%= msg.created_at.to_date %>
                    <% end %>
                <% end %>
            </ul>
        </div>
    </div>
    
    <div class="history-dropdown">
        <h4><%= link_to "Seen", "#", id: "history-link" %><b class="caret"></b></h4>
        <div class="items-list", id="history">    
            <ul class="messages">
                <% @messages.each do |msg| %>
                    <% if msg.seen %>
                    
                        <% if msg.creator_type="Administrator" %>
                            <% user=Administrator.find(msg.creator_id) %>
                        <% else %>
                            <% user=PAtient.find(msg.creator_id) %>
                        <% end %>
                    
                        <li id="message-"+<%= msg.id %>><%= link_to msg.subject + " | by: " + user.name, msg %></li>
                        <br><%= msg.created_at.to_date %>
                    <% end %>
                <% end %>
            </ul>
        </div>
    </div>
</div>