config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/signup_patient', to: 'patients#new'
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  patch '/edit_session', to: "sessions#update"
  delete "/logout", to: "sessions#destroy"
  
  resources :patients
  resources :contents
  resources :messages
  resources :appointments
  resources :administrators
  resource :calendar, only: [:show], controller: :calendar
  
end

app/views/layouts/_flash.html.erb
<div id="flash-container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= simple_format(message) %></div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Created by Robert G.
    </small>
    <nav>
        <ul>
            <% if current_user_admin_sh? and current_user_sh.supervisor %>
                <li id="edit_status"><%= render "shared/edit_mode" %></li>
            <% end %>
            <li><%= link_to "About us", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- _sh: sessions_helper -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Dr. Test & Co.", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About us", about_path %></li>
        <% if logged_in_sh? %>
          <li><%= link_to "Calendar", calendar_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Messages <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Index", messages_path %></li>
              <li><%= link_to "New", new_message_path %></li>
            </ul>
          </li>
          <% if current_user_admin_sh? %>
            <li><%= link_to "Appointments", appointments_path %></li>
            <% if current_user_sh.supervisor %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Administrators <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Index", administrators_path %></li>
                  <li><%= link_to "Create", new_administrator_path %></li>
                </ul>
              </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Patients <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Index", patients_path %></li>
                <li><%= link_to "Create", new_patient_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user_sh %></li>
              <% if(current_user_admin_sh? and current_user_sh.supervisor) %>
                <li><%= link_to "Settings", edit_administrator_path(current_user_sh) %></li>
              <% else %>
                <li><%= link_to "Settings", edit_patient_path(current_user_sh) %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>


      <%= render "layouts/header" %>
      
      <%= render "layouts/flash" %>
      
      <%= yield %>
      
      <%= render "layouts/footer" %>

</body>
</html>